#!/bin/csh -f

#****************************************************************************
#***
#***   Copyright (c) 1997 by Max Moroz and ABKGroup, UCLA VLSI CAD Laboratory,
#***    UCLA Computer Science Department, Los Angeles, CA 90095-1596 USA, 
#***    and by the Regents of the University of California.    
#***    All rights reserved.   
#***
#***    No portion of this package may be used, copied, or transmitted for
#***    any purpose, including any research or commercial purpose,
#***    without the express written consent of Professor Andrew B. Kahng,
#***    UCLA Computer Science Department, 3713 Boelter Hall, Los Angeles,
#***    CA 90095-1596 USA.   Any copy made of this file must include this
#***    notice.    ABKGroup and the Regents of the University of California
#***    retain title to all copies of this file and/or its compiled
#***    derivatives.
#***
#*****************************************************************************/

set DIFF=/usr/bin/diff
set WC=/usr/bin/wc
set PROG=CombiTest 

/bin/rm -f seeds.{in,out} *.diff >& /dev/null

echo " ------------  Running test 0 ..." > new.out
echo -n Running test 0 ...
${PROG}0.exe  >> new.out
echo Ok

echo " ------------  Running test 1 ..." >> new.out
echo -n Running test 1 ...
${PROG}1.exe  >> new.out
echo Ok

echo " ------------  Running test 2 ..." >> new.out
echo -n Running test 2 ...
${PROG}2.exe  >>& new.out
echo Ok

echo "------------  Running test 3 ..." >> new.out
echo -n Running test 3 ...
${PROG}3.exe 5 >> new.out
echo Ok

echo "------------  Running test 4a..." >> new.out
echo -n Running test 4a...
${PROG}4.exe 4 >> new.out
echo Ok

echo "------------  Running test 4b..." >> new.out
echo -n Running test 4b...
${PROG}4.exe 9 >> new.out
echo Ok

#echo "------------  Running test 4c..." >> new.out
#echo -n Running test 4c...
#${PROG}4.exe 10 >> new.out
#echo Ok

#echo "------------  Running test 4d..." >> new.out
#echo -n Running test 4d...
#${PROG}4.exe 11 >> new.out
#echo Ok


echo "------------  Running test 5a..." >> new.out
echo -n Running test 5a...
${PROG}5.exe 4  >> new.out
echo Ok

echo "------------  Running test 5b..." >> new.out
echo -n Running test 5b...
${PROG}5.exe 3 3 >> new.out
echo Ok

egrep -v "(Created|sec|User|Platform|Memory us)" new.out > newout.notime
egrep -v "(Created|sec|User|Platform|Memory us)" expected.out > expectedout.notime
$DIFF newout.notime expectedout.notime > diffs.notime

echo " "
echo Differences from precomputed results
echo "  lines:  words:  bytes:    error log:"
$WC diffs.notime

