#!/bin/csh -f
dmake DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS='-g -DABKDEBUG $(ABKSYMBOLS)'  CCFLAGS="-fPIC -Wall -pedantic -pipe" CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared" LDFINAL="g++" SOLABEL="" SODIRKEY="-Wl,-rpath,"  YACC_LIB="" $1 $2 $3
# SONAMEKEY="-Wl,-soname," 
