#!/bin/csh -f

#****************************************************************************
#***
#***   Copyright (c) 1997 by Max Moroz and ABKGroup, UCLA VLSI CAD Laboratory,
#***    UCLA Computer Science Department, Los Angeles, CA 90095-1596 USA, 
#***    and by the Regents of the University of California.    
#***    All rights reserved.   
#***
#***    No portion of this package may be used, copied, or transmitted for
#***    any purpose, including any research or commercial purpose,
#***    without the express written consent of Professor Andrew B. Kahng,
#***    UCLA Computer Science Department, 3713 Boelter Hall, Los Angeles,
#***    CA 90095-1596 USA.   Any copy made of this file must include this
#***    notice.    ABKGroup and the Regents of the University of California
#***    retain title to all copies of this file and/or its compiled
#***    derivatives.
#***
#*****************************************************************************/

set DIFF=/usr/bin/diff
set WC=/usr/bin/wc
set PROG=FilledHierTest 

/bin/rm -f seeds.{in,out} *.diff >& /dev/null

echo "------------  Running test 1 ..." > new.out
echo -n Running test 1 ...
${PROG}0.exe  -f TESTS/size99.hcl -hgraphAux TESTS/size99.aux>> new.out
echo Ok
 
egrep -v "(Created|arning|sec|took|User|Platform|Memory)" new.out > newout.notime
egrep -v "(Created|arning|sec|took|User|Platform|Memory)" expected.out > expectedout.notime
$DIFF newout.notime expectedout.notime > diffs.notime

echo " "
echo Differences from precomputed results
echo "  lines:  words:  bytes:    error log:"
$WC diffs.notime

