#!/bin/csh -f
# -Wall -pedantic are not used here because they complain about
# [many] local variables that have been optimized out
make  DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS='-O3 -funroll-loops $(ABKSYMBOLS)' CCFLAGS="-fPIC -pipe" CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared" LDFINAL="g++" SODIRKEY="-Wl,-rpath," SOLABEL=""  YACC_LIB="" $1 $2 $3 $4 $5
#SODIRKEY="-Wl,-rpath," SOLABEL="" $1
