#!/bin/csh -f
make MAKE="make-gnu" DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS="-g -DABKDEBUG"  CCFLAGS="-fPIC -Wall -pedantic -pipe -Wno-deprecated" CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared" LDFINAL="g++" SOLABEL="" SODIRKEY="-Wl,-rpath,"  $1 $2 $3 $4 $5
# SONAMEKEY="-Wl,-soname," 
