#!/bin/csh -f

#**************************************************************************
#**
#**    Copyright (c) 1995-1997 by ABKGroup, UCLA VLSI CAD Laboratory,
#**    UCLA Computer Science Department, Los Angeles, CA 90095-1596 USA,
#**    and by the Regents of the University of California.
#**    All rights reserved.
#**
#**    No portion of this file may be used, copied, or transmitted for
#**    any purpose, including any research or commercial purpose,
#**    without the express written consent of Professor Andrew B. Kahng,
#**    UCLA Computer Science Department, 3713 Boelter Hall, Los Angeles,
#**    CA 90095-1596 USA.   Any copy made of this file must include this
#**    notice.    ABKGroup and the Regents of the University of California
#**    retain title to all copies of this file and/or its compiled
#**    derivatives.
#**
#**************************************************************************/


set DIFF=/usr/bin/diff
set WC=/usr/bin/wc
set PROG=dbTest 

echo "" > new1.out
foreach i (~data/BENCH/AUX/*ql.aux)
  echo $i
  nice -15 ${PROG}0 -f $i >> new1.out
end

egrep -v "(Created|sec)" new1.out > newout.notime
egrep -v "(Created|sec)" expected1.out > expectedout.notime
$DIFF newout.notime expectedout.notime > diffs1.notime

echo " "
echo Differences from precomputed results
$WC diffs1.notime
