UCLA scl 1.0
#Created : fill in later
#User : fill in later
#Platform : fill in later

Numrows : 11

CoreRow Horizontal
 Coordinate	:	1
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	2
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	3
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	4
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	5
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	6
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	7
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	8
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	9
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	10
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
CoreRow Horizontal
 Coordinate	:	11
 Height		:	1
 Sitewidth	:	1
 Sitespacing	:	1
 Siteorient	:	N
 Sitesymmetry	:	Y
 SubrowOrigin	:	1 Numsites :	25
End
