UCLA scl    1.0
# Host : Linux belka 2.2.15 #1 Thu Jun 1 10:47:16 EST 2000 i686 unknown
# Translation date: Mon Oct 16 20:36:26 EDT 2000
NumRows : 15
CoreRow Horizontal
 Coordinate   : 1
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 2
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 3
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 4
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 5
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 6
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 7
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 8
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 9
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 10
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 11
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 12
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 13
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 14
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
CoreRow Horizontal
 Coordinate   : 15
 Height       : 1
 Sitewidth    : 1
 Sitespacing  : 1
 Siteorient   : N
 Sitesymmetry : Y
 SubrowOrigin : 0 Numsites     : 15
End
