#!/bin/csh -f

#**************************************************************************
#**
#**    Copyright (c) 1995-1997 by ABKGroup, UCLA VLSI CAD Laboratory,
#**    UCLA Computer Science Department, Los Angeles, CA 90095-1596 USA,
#**    and by the Regents of the University of California.
#**    All rights reserved.
#**
#**    No portion of this file may be used, copied, or transmitted for
#**    any purpose, including any research or commercial purpose,
#**    without the express written consent of Professor Andrew B. Kahng,
#**    UCLA Computer Science Department, 3713 Boelter Hall, Los Angeles,
#**    CA 90095-1596 USA.   Any copy made of this file must include this
#**    notice.    ABKGroup and the Regents of the University of California
#**    retain title to all copies of this file and/or its compiled
#**    derivatives.
#**
#**************************************************************************/

set DIFF=/usr/bin/diff
set WC=/usr/bin/wc

set PROG_BB="RowIroningTest1.exe -smPlAlgo Branch"
set PROG_DP="RowIroningTest1.exe -smPlAlgo DynamicP"

/bin/rm -f seeds.out seeds.in

echo "___ branch and bound tests ______" > new.out
echo "___ branch and bound tests ______" 
echo "___ size 7 tests _____" >> new.out
echo "___ size 7 tests _____" 
$PROG_BB -f TESTS/C432a.aux >> new.out
$PROG_BB -f TESTS/primary1.nf.WS10.aux >> new.out
# $PROG_BB -f TESTS/intel.aux >> new.out

echo "___ Dynamic Programming tests _____" >> new.out
echo "___ Dynamic Programming tests _____" 

echo "___ size 8 tests _____" >> new.out
echo "___ size 8 tests _____" 
$PROG_DP -f TESTS/C432a.aux -ironWindow 8 >> new.out
$PROG_DP -f TESTS/primary1.nf.WS10.aux -ironWindow 8 >> new.out
#$PROG_DP -f TESTS/intel.aux -ironWindow 8 >> new.out

egrep -v "(Created|took|User|Platform|Memory)" new.out > newout.notime
egrep -v "(Created|took|User|Platform|Memory)" expected.out > expectedout.notime

$DIFF newout.notime expectedout.notime    >  diffs.notime

echo " "
echo Differences from precomputed results
$WC diffs.notime

rm -f seeds.{out,in} expectedout.notime

