#!/bin/csh -f
make MAKE="make-gnu" DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS='-g -DABKDEBUG $(ABKSYMBOLS)'  CCFLAGS="-fPIC -Wall -pedantic -pipe" CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared" LDFINAL="g++" SOLABEL="" SODIRKEY="-Wl,-rpath," YACC_LIB="" $1 $2 $3 $4 $5
# SONAMEKEY="-Wl,-soname," 
