#!/bin/csh -f

#**************************************************************************
#**
#**    Copyright (c) 1995-1997 by ABKGroup, UCLA VLSI CAD Laboratory,
#**    UCLA Computer Science Department, Los Angeles, CA 90095-1596 USA,
#**    and by the Regents of the University of California.
#**    All rights reserved.
#**
#**    No portion of this file may be used, copied, or transmitted for
#**    any purpose, including any research or commercial purpose,
#**    without the express written consent of Professor Andrew B. Kahng,
#**    UCLA Computer Science Department, 3713 Boelter Hall, Los Angeles,
#**    CA 90095-1596 USA.   Any copy made of this file must include this
#**    notice.    ABKGroup and the Regents of the University of California
#**    retain title to all copies of this file and/or its compiled
#**    derivatives.
#**
#**************************************************************************/

set DIFF=/usr/bin/diff
set WC=/usr/bin/wc

set PROG="CapoTest"

/bin/rm -f seeds.out seeds.in

cp TESTS/seeds.in seeds.in


echo "Running CapoPlacer on saurabh1 (20 cells)" 
echo "Running CapoPlacer on saurabh1 (20 cells)" > new.out
${PROG}1.exe -f TESTS/saurabh1.aux -verb 6_6_6  >>& new.out

echo "Running CapoPlacer on primary1 w/ 02% whitespace"
echo "Running CapoPlacer on primary1 w/ 02% whitespace" >> new.out

${PROG}1.exe -f TESTS/primary1.nf.WS02.aux -verb 6_6_6 -skipOverlapping >>& new.out

echo "Running CapoPlacer on primary1 w/ 10% whitespace"
echo "Running CapoPlacer on primary1 w/ 10% whitespace" >> new.out

${PROG}1.exe -f TESTS/primary1.nf.WS10.aux -verb 6_6_6 -skipOverlapping >>& new.out

egrep -vi "(#|Time|Created|took|sec|User|Platform|Memory)" new.out > newout.notime
egrep -vi "(#|Time|Created|took|sec|User|Platform|Memory)" expected.out > expectedout.notime

$DIFF newout.notime expectedout.notime    >  diffs.notime

echo " "
echo Differences from precomputed results
$WC diffs.notime

echo "** Depending on your platform, there may be large differences "
echo "** in this test -- that's ok "
echo "** Check for crashes; check the final WLs number (they must be close)"

rm -f seeds.{out,in} expectedout.notime

