#!/bin/csh -f
# -Wall -pedantic are not used here because they complain about
# [many] local variables that have been optimized out
dmake  MAKE="dmakeOpt-gnu" DEPENDOPT="-MM" CC4LIBS="g++" OPTFLAGS='-O3 -funroll-loops $(ABKSYMBOLS)' CCFLAGS="-fPIC -pipe" CC='g++ $(OPTFLAGS) $(CCFLAGS)' LD="g++ -shared" LDFINAL="g++" SODIRKEY="-Wl,-rpath," SOLABEL="" QLIBS="" YACC_LIB="" $1 $2 $3
#SODIRKEY="-Wl,-rpath," SOLABEL="" $1
