#!/bin/csh -f

#/**************************************************************************
#***    
#*** Copyright (c) 2000-2002 Regents of the University of Michigan,
#***               Saurabh N. Adya and Igor L. Markov
#***
#***  Contact author(s): abk@cs.ucsd.edu, imarkov@umich.edu
#***  Original Affiliation:   University of Michigan, EECS Depatrment
#***                          1301 Beal Ave. Ann Arbor, MI 48109-2122
#***
#***  Permission is hereby granted, free of charge, to any person obtaining 
#***  a copy of this software and associated documentation files (the
#***  "Software"), to deal in the Software without restriction, including
#***  without limitation 
#***  the rights to use, copy, modify, merge, publish, distribute, sublicense, 
#***  and/or sell copies of the Software, and to permit persons to whom the 
#***  Software is furnished to do so, subject to the following conditions:
#***
#***  The above copyright notice and this permission notice shall be included
#***  in all copies or substantial portions of the Software.
#***
#*** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
#*** EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
#*** OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
#*** IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#*** CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
#*** OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
#*** THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#***
#***
#***************************************************************************/

set DIFF=/usr/bin/diff
set WC=/usr/bin/wc

set PROG="CongestionMapsTest0.exe -plotCongMap out"

/bin/rm -f seeds.out seeds.in

echo "___ Congestion Map tests" > new.out
#$PROG -f TESTS/intel.aux >> new.out
#cat out.m >> new.out
$PROG -f TESTS/primary1.nf.WS02.aux >> new.out
cat out.m >> new.out

egrep -v "(Created|took|User|Platform|Memory)" new.out > newout.notime
egrep -v "(Created|took|User|Platform|Memory)" expected.out > expectedout.notime

$DIFF newout.notime expectedout.notime    >  diffs.notime

echo " "
echo Differences from precomputed results
$WC diffs.notime

rm -f seeds.{out,in} expectedout.notime out.m outX.m outY.m

